/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    AutoText: typeof import('./../src/components/core/AutoText.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    BattleModeDropdown: typeof import('./../src/components/data/BattleModeDropdown.vue')['default']
    BlockUI: typeof import('primevue/blockui')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataList: typeof import('./../src/components/core/DataList.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Description: typeof import('./../src/components/preview/Description.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Fluid: typeof import('primevue/fluid')['default']
    ImageEditor: typeof import('./../src/components/core/ImageEditor.vue')['default']
    ImageFlow: typeof import('./../src/components/preview/ImageFlow.vue')['default']
    Inplace: typeof import('primevue/inplace')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Level: typeof import('./../src/components/data/Level.vue')['default']
    LevelColumn: typeof import('./../src/components/data/LevelColumn.vue')['default']
    MemberList: typeof import('./../src/components/pick/MemberList.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Stage: typeof import('./../src/components/preview/Stage.vue')['default']
    Stars: typeof import('./../src/components/data/Stars.vue')['default']
    Step: typeof import('primevue/step')['default']
    StepList: typeof import('primevue/steplist')['default']
    Stepper: typeof import('primevue/stepper')['default']
    StudentAvatar: typeof import('./../src/components/data/StudentAvatar.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TeamArray: typeof import('./../src/components/preview/TeamArray.vue')['default']
    TeamListItem: typeof import('./../src/components/pick/TeamListItem.vue')['default']
    Teams: typeof import('./../src/components/preview/Teams.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    VideoCover: typeof import('./../src/components/preview/VideoCover.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
